### ISSUE TITLE
First Meeting: April 14th, Aeronaut Brewery, 8:00pm

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/somerville.js#1]
I'm curious who else is around and wants to go?

**Comment by gr2m** [comment]
here :raised_hands:

**Comment by RichardLitt** [comment]
Ok! Let's go!

**Comment by dsfields** [comment]
Sounds like fun.  See you there.

**Comment by cspanring** [comment]
Conflict with Ember.js meetup this time... :-1:

**Comment by RichardLitt** [comment]
Awww that sucks. Sorry! Weigh in next time? I'm not an Emberite. :(

**Comment by dsfields** [comment]
What's the agenda for the meetup?

**Comment by gr2m** [comment]
@dsfields :beers:, and then maybe some :beers: and :speech_balloon: and maybe a :wine_glass:, maybe even 🍟🍕🍗

**Comment by RichardLitt** [comment]
Note: This is a 21+ meetup. **If anyone wants to join who is underage, please contact me by email (private) or say so here. We can include you somehow.**

**Comment by courajs** [comment]
Aeronaut's [site](http://www.aeronautbrewing.com) is really well designed btw

**Comment by RichardLitt** [comment]
It was great!
