### ISSUE TITLE
Second Meeting: Aug 10, Wednesday at Diesel Cafe in Davis

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/somerville.js#2]
Hello everyone! It is time for a second SomervilleJS. 

I propose Wednesday, August 10 at **Diesel Cafe** in Davis at 8:00pm.

That last one was at Aeronaut and was great; but that's strictly for booze, and we should switch it up now and then to be inclusive.

**Comment by leobalter** [comment]
works for me! count me in!

**Comment by aredridel** [comment]
Sounds fantastic!

**Comment by calvinfroedge** [comment]
+1 if I'm welcome =)

**Comment by RichardLitt** [comment]
You are!

**Comment by jimkang** [comment]
I'm pro-coffee shop meetup! I might have to be a little late, but I'll try to make it!

**Comment by RichardLitt** [comment]
By the way: please tell people! I don't know everyone.

**Comment by RichardLitt** [comment]
Meeting tonight!

**Comment by cspanring** [comment]
@calvinfroedge I was trying to refer to this talk about DOM diffing by Tim Branyen at a BostonJS meetup, where he demoed different DOM manipulation approaches: https://diffhtml.org

**Comment by RichardLitt** [comment]
This was the book @aredridel suggested: https://www.amazon.com/gp/product/0195019199/ref=ox_sc_act_title_1?ie=UTF8&psc=1&smid=ATVPDKIKX0DER

**Comment by RichardLitt** [comment]
A rousing success!
