### ISSUE TITLE
SomervilleJS meeting on Tuesday?

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/somerville.js#6]
Anyone around?

**Comment by jimkang** [comment]
Hey! Wednesday would be better, but I might be able to make Tuesday if it's late. When were you thinking?

**Comment by RichardLitt** [comment]
Wednesday works for me! I dunno; maybe just a table at Diesel?

**Comment by jimkang** [comment]
So, my schedule is mildly weird; I'm open during the day (maybe lunch is a good time?) on Wednesday, and on Thursday night a friend and I have a project night at Panera in Porter Sq. that maybe we could just merge with this. Any preferences there?

**Comment by RichardLitt** [comment]
Can't make Thursday night, unfortunately. Lunch on Wednesday sounds fun, but sounds more like Richard-and-Jim and less SomervilleJS. As you're the only one who responded, might be fun though. :)

**Comment by jimkang** [comment]
Good point! I could try to make Wednesday night to keep things open for anyone that might see this late, but I'd have to show up after 8.

**Comment by aredridel** [comment]
Aw, this week is full for me!

**Comment by RichardLitt** [comment]
@aredridel <3 Have a good one, then. 

@jimkang Seeing the lack of reaction on Twitter (Perhaps because BostonJS is this week, too?), I'm moving this to Twitter DMs. :)

**Comment by RichardLitt** [comment]
@jimkang I can't remember your twitter. :/ @DeathMountain or something? Want to ping me about lunch tomorrow?

**Comment by jimkang** [comment]
Oh, I quit Twitter. I use ye olde email: jimkang@fastmail.com

**Comment by jimkang** [comment]
@aredridel :wave:

**Comment by aredridel** [comment]
👋 Sorry I couldn't make it — this week was wedged full!

**Comment by RichardLitt** [comment]
@aredridel No worries! Jim and I had a nice lunch. Next time I'll try to give more warning!
